# Tensor with Tensorflow

In [1]:
import tensorflow as tf

In [2]:
# 0D Tensor (Scalar)

scalar = tf.constant(1)
print(scalar)
print(tf.rank(scalar))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [3]:
# 1D Tensor (Vector)
vector = tf.constant([1, 2, 3])
print(vector)
print(tf.rank(vector))


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
# 2D Tensor (Matrix)

matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)
print(tf.rank(matrix))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# 3D Tensor
tensor3d = tf.constant(
    [
        [
            [1, 2], [3, 4]
        ],
        [
            [5, 6], [7, 8]
        ]
    ]
)
print(tensor3d)
print(tf.rank(tensor3d))

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## 텐서 타입

|Data Type|TF type|Description|
|---|---|---|
|DT_FLOAT|tf.float32|32비트 부동 소수|
|DT_DOUBLE|tf.float64|64비트 부동 소수|
|DT_INT8|tf.int8|8비트 부호 있는 정수|
|DT_INT16|tf.int16|16비트 부호 있는 정수|
|DT_INT32|tf.int32|32비트 부호 있는 정수|
|DT_INT64|tf.int64|64비트 부호 있는 정수|
|DT_UINT8|tf.uint8|8비트 부호 없는 정수|
|DT_STRING|tf.string|가변 길이 바이트 배열. Tensor의 각 원소는 바이트 배열.|
|DT_BOOL|tf.bool|불리언|
|DT_COMPLEX64|tf.complex64|2개의 32비트 부동 소수로 만든 복소수 : 실수부 + 허수부|
|DT_COMPLEX128|tf.complex128|2개의 64비트 부동 소수로 만든 복소수 : 실수부 + 허수부|
|DT_QINT8|tf.qint8|8비트 부호 있는 정수로 quantized Ops에서 사용|
|DT_QINT32|tf.qint32|32비트 부호 있는 정수로 quantized Ops에서 사용|
|DT_QUINT8|tf.quint8|8비트 부호 없는 정수로 quantized Ops에서 사용|

In [6]:
# default int32
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [7]:
# float32 
# 실수의 경우 default float32
f = tf.constant(2.)
print(f)

tf.Tensor(2.0, shape=(), dtype=float32)


In [8]:
# string
s = tf.constant("chan")
print(s)

tf.Tensor(b'chan', shape=(), dtype=string)


In [9]:
# type 지정
f16 = tf.constant(2., dtype=tf.float16)
print(f16)

tf.Tensor(2.0, shape=(), dtype=float16)


## 텐서 변환

### 텐서 타입 변환
- tf.cast

In [10]:
f32 = tf.cast(f16, tf.float32)
print(f32)

tf.Tensor(2.0, shape=(), dtype=float32)


### 텐서 형상 변환
- tf.reshape

In [11]:
x = tf.constant([[1], [2], [3]])
print(x)
print(x.shape)

y = tf.reshape(x, (1, 3))
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


### 텐서 전치
- tf.transpose

In [12]:
print(y)
print(tf.transpose(y))
print(y.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(1, 3)


### 차원 압축
- tf.squeeze

In [13]:
print(x)
print(tf.squeeze(x))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### 차원 추가
- tf.expand_dims

In [14]:
print(y)
print(tf.expand_dims(y, axis=0))
print(tf.expand_dims(y, axis=1))
print(tf.expand_dims(y, axis=2))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


### 텐서 분리
- tf.split

In [15]:
print(x)
print(tf.split(x, 3))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
[<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[3]], dtype=int32)>]


### 텐서 연결
- tf.concat

In [16]:
print(x)
print(tf.concat([x, x], axis=0))
print(tf.concat([x, x], axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


### 인덱싱
- tf.gather

In [17]:
tensor1d = tf.constant([[1, 2, 3], [4, 5, 6]])
gather_axis0 = tf.gather(params=tensor1d, indices=[(0,0), (1,0)], axis=0)
print(gather_axis0)
gather_axis1 = tf.gather(params=tensor1d, indices=[(0,0), (1,0)], axis=1)
print(gather_axis1)

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [1 2 3]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[1 1]
  [2 1]]

 [[4 4]
  [5 4]]], shape=(2, 2, 2), dtype=int32)


## 텐서 변환 정리
|Function|Description|
|---|---|
|tf.shape|텐서의 구조 확인|
|tf.size|텐서의 크기 확인|
|tf.rank|텐서의 랭크 확인|
|tf.reshape|텐서의 원소는 그대로 유지하면서 텐서의 구조 변경|
|tf.squeeze|텐서에서 크기가 1인 차원 삭제|
|tf.expand_dims|텐서에 차원을 추가|
|tf.slice|텐서의 일부분 삭제|
|tf.split|텐서를 한 차원을 기준으로 여러 개의 텐서로 분할|
|tf.tile|한 텐서를 여러 번 중복해서 늘려 새 텐서 생성|
|tf.concat|한 차원을 기준으로 텐서 연결|
|tf.reverse|한 차원을 기준으로 텐서를 역전|
|tf.transpose|텐서 전치|
|tf.gather|주어진 인덱스에 따라 텐서의 원소를 인덱싱|

## 텐서 연산
|연산자 오버로딩|함수|연산|
|---|---|---|
|+|tf.add|더하기 연산|
|-|tf.subtract|빼기 연산|
|*|tf.multiply|곱하기 연산|
|/|tf.divide|나누기 연산|
|@|tf.matmul|행렬곱 연산|
||tf.reduce_max|텐서 값 중 최대값|
||tf.argmax|최대값의 위치 반환|

#### 0차원 텐서 연산

In [18]:
# 더하기 빼기
print(tf.constant(1) + tf.constant(2))
print(tf.constant(1) - tf.constant(2))
print(tf.add(tf.constant(1), tf.constant(2)))
print(tf.subtract(tf.constant(1), tf.constant(2)))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)


In [19]:
# 곱하기 나누기
print(tf.constant(1) * tf.constant(2))
print(tf.constant(1) / tf.constant(2))
print(tf.multiply(tf.constant(1), tf.constant(2)))
print(tf.divide(tf.constant(1), tf.constant(2)))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)


In [20]:
# 서로 다른 타입의 경우 연산 불가능

# InvalidArgumentError
tf.constant(1, dtype=tf.int8) + tf.constant(2, dtype=tf.int16)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int8 tensor but is a int16 tensor [Op:AddV2] name: 

In [ ]:
# 타입 변환 필요
tf.cast(tf.constant(1, dtype=tf.int8), dtype=tf.int16) + tf.constant(2, dtype=tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=3>

#### 1차원 이상의 텐서 연산

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


#### 2차원 텐서 연산

In [22]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 2],[3, 4]])

print(a + b)
print(a - b)
print(a * b)
print(a @ b)
print(a / b)

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float64)


In [37]:
# reduce_max
matrix = tf.constant([[1, 2], [4, 3]])
print(tf.reduce_max(matrix, axis=None))
print(tf.reduce_max(matrix, axis=0))
print(tf.reduce_max(matrix, axis=1))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [43]:
# argmax
matrix = tf.constant([[1, 2], [4, 3]])
print(tf.argmax(matrix, axis=None))
print(tf.argmax(matrix, axis=0))
print(tf.argmax(matrix, axis=1))

tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([1 0], shape=(2,), dtype=int64)


In [54]:
# softmax

# softmax 연산에 허용되는 타입은 [half, bfloat16, float, double]
matrix = tf.constant([[1, 2], [4, 3]])
# InvalidArgumentError 

matrix = tf.constant([[1, 2], [7, 3]], dtype=tf.float32)
print(tf.nn.softmax(matrix, axis=None))
print(tf.nn.softmax(matrix, axis=0))
print(tf.nn.softmax(matrix, axis=1))

tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.98201376 0.01798621]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.00247262 0.26894143]
 [0.9975274  0.7310586 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.98201376 0.01798621]], shape=(2, 2), dtype=float32)
tf.Tensor([0.98201376 0.01798621], shape=(2,), dtype=float32)
